version: 2
jobs:
  build:
    docker:
        - image: elexy/circleci_s2i:0.0.2
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure
          command: |
            if [[ -z $NODE_VERSION || -z $V8_VERSION || -z $NPM_VERSION || -z $IMAGE_TAG ]]; then
              if [[ -z $VERSION || -z $V8 || -z $NPM || -z $TAG ]]; then
                echo 'one or more variables are undefined, aborting build.'
                echo "Assuming build script debug mode"
                export VERSION=6.12.1
                export V8=5.1.281.109
                export NPM=3.10.10
                export TAG=test-only
                export NODE_VERSION=$VERSION
                export V8_VERSION=$V8
                export NPM_VERSION=$NPM
                export IMAGE_TAG=$TAG

                ./configure --version "$VERSION" \
                        --v8 "$V8" \
                        --npm "$NPM" \
                        --tag "$TAG"
              else
                export NODE_VERSION=$VERSION
                export V8_VERSION=$V8
                export NPM_VERSION=$NPM
                export IMAGE_TAG=$TAG

                ./configure --version "$VERSION" \
                        --v8 "$V8" \
                        --npm "$NPM" \
                        --tag "$TAG" \
                        --lts "$LTS" \
                        --major "$MAJOR" \
                        --minor "$MINOR"
              fi
            fi

      - run:
          name: Build
          command: make build
      - run:
          name: Docker squash
          command: make squash
      - run:
          name: Test
          command: make test
      - run:
          name: Tag LTS if this is an LTS release
          command: make tag
      - run:
          name: Publish
          command: |
            make publish
            echo ${RH_DOCKER_PASS} | docker login -u unused registry.rhc4tp.openshift.com:443 --password-stdin
            RH_TARGET="registry.rhc4tp.openshift.com:443/p936591153adf2db17145e97afc3511f2549b5dfa3/redhat7-s2i-nodejs:${TAG}"
            docker tag nearform/rhel7-s2i-nodejs:${TAG} ${RH_TARGET}
            docker push ${RH_TARGET}
      - run:
          name: Archive
          command: |
            make archive
            sudo pip install --no-deps s3cmd
            echo "access_key = $AWS_ACCESS_KEY_ID" >> ~/.s3cfg
            echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> ~/.s3cfg
