version: 2
jobs:
  build:
    docker:
        - image: elexy/circleci_s2i:0.0.2
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure
          command: |
            export VERSION="8.9.0"
            export V8="6.1.534.42"
            export NPM="5.4.2"
            export TAG="8.9.0"

            if [[ -z $NODE_VERSION || -z $V8_VERSION || -z $NPM_VERSION || -z $IMAGE_TAG ]]; then
              if [[ -z $VERSION || -z $V8 || -z $NPM || -z $TAG ]]; then
                echo 'one or more variables are undefined, aborting build.'
                exit 1
              else
                export NODE_VERSION=$VERSION
                export V8_VERSION=$V8
                export NPM_VERSION=$NPM
                export IMAGE_TAG=$TAG
              fi
            fi
            if [[ -z $LTS_TAG ]]; then
              ./configure --version $NODE_VERSION \
                          --v8 $V8_VERSION \
                          --npm $NPM_VERSION \
                          --tag $IMAGE_TAG
            else
              ./configure --version $NODE_VERSION \
                          --v8 $V8_VERSION \
                          --npm $NPM_VERSION \
                          --tag $IMAGE_TAG \
                          --lts-tag $LTS_TAG
            fi
      - run:
          name: Build
          command: make build
      - run:
          name: Docker squash
          command: make squash
      - run:
          name: Test
          command: make test
      - run:
          name: Tag LTS if this is an LTS release
          command: make tag
      - run:
          name: Publish
          command: |
            MAJOR_VERSION="${NODE_VERSION%%.*}"
            export VERSION_X=$(echo "$MAJOR_VERSION.x")

            make publish
